ProjectSkripsi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('account/', include('account.urls', namespace='account')),
    path('home/', include('home.urls', namespace='home'))
]

home/urls.py
from django.urls import path, include
from home.views import \
    view_data_cbrawit, view_data_cbmerah, \
    view_normalisasi_cbmerah, view_normalisasi_cbrawit, \
    view_training_cbrawit, view_training_cbmerah, view_testing_cbrawit, view_testing_cbmerah, view_mse_cbmerah, \
    view_mse_cbrawit, view_denormalisasi_cbmerah, view_denormalisasi_cbrawit, view_chart_cbmerah, view_chart_cbrawit, \
    view_data_user, view_testing_prediksi_cbrawit, view_testing_prediksi_cbmerah

app_name = 'home'

urlpatterns = [
    path('data-user/', view_data_user.IndexView.as_view(), name='data-user'),
    path('detail-user/<int:pk>/', view_data_user.detail, name='detail-user'),
    path('edit-user/<int:pk>/', view_data_user.edit, name='edit-user'),
    path('create-user/', view_data_user.create, name='create-user'),
    path('delete-user/<int:pk>/', view_data_user.delete, name='delete-user'),
    path('logout', view_data_user.logout_view, name='logout'),

    path('dashboard/', view_data_user.dashboard, name='dashboard'),

    path('data-cbrawit/', view_data_cbrawit.IndexView.as_view(), name='home_view'),
    path('detail-cbrawit/<int:pk>/', view_data_cbrawit.DataDetailView.as_view(), name='detail'),
    path('edit-cabairawit/<int:pk>/', view_data_cbrawit.edit, name='edit'),
    path('create-cabairawit/', view_data_cbrawit.create, name='create'),
    path('delete-cabairawit/<int:pk>/', view_data_cbrawit.delete, name='delete'),
    path('proses-data-cbrawit/', view_data_cbrawit.DataView.as_view(), name='data_cbrawit'),

    path('data-cbmerah/', view_data_cbmerah.IndexView.as_view(), name='homeview_cbmerah'),
    path('detail-cbmerah/<int:pk>/', view_data_cbmerah.DataDetailView.as_view(), name='detail_cbmerah'),
    path('edit-cbmerah/<int:pk>/', view_data_cbmerah.edit, name='edit_cbmerah'),
    path('create-cbmerah/', view_data_cbmerah.create, name='create_cbmerah'),
    path('delete-cbmerah/<int:pk>/', view_data_cbmerah.delete, name='delete_cbmerah'),
    path('proses-data-cbmerah/', view_data_cbmerah.DataView.as_view(), name='data_cbmerah'),

    path('proses-normalisasi-cbrawit/', view_normalisasi_cbrawit.IndexView.as_view(), name='normalisasi_cbrawit'),
    path('proses-normalisasi-cbmerah/', view_normalisasi_cbmerah.IndexView.as_view(), name='normalisasi_cbmerah'),
    path('proses-training-cbrawit/', view_training_cbrawit.IndexView.as_view(), name='training_cbrawit'),
    path('proses-training-cbmerah/', view_training_cbmerah.IndexView.as_view(), name='training_cbmerah'),
    path('proses-testing-cbrawit/', view_testing_cbrawit.IndexView.as_view(), name='testing_cbrawit'),
    path('proses-testing-cbmerah/', view_testing_cbmerah.IndexView.as_view(), name='testing_cbmerah'),
    path('proses-mse-cbrawit/', view_mse_cbrawit.IndexView.as_view(), name='mse_cbrawit'),
    path('proses-mse-cbmerah/', view_mse_cbmerah.IndexView.as_view(), name='mse_cbmerah'),
    path('proses-denormalisasi-cbrawit/', view_denormalisasi_cbrawit.IndexView.as_view(), name='denormalisasi_cbrawit'),
    path('proses-denormalisasi-cbmerah/', view_denormalisasi_cbmerah.IndexView.as_view(), name='denormalisasi_cbmerah'),
    path('proses-chart-cbmerah/', view_chart_cbmerah.IndexView.as_view(), name='chart_cbmerah'),
    path('proses-chart-cbrawit/', view_chart_cbrawit.IndexView.as_view(), name='chart_cbrawit'),
    path('proses-data-chart-cbmerah/', view_chart_cbmerah.get_chart, name='data_chart_cbmerah'),
    path('proses-data-chart-cbrawit/', view_chart_cbrawit.get_chart, name='data_chart_cbrawit'),

    path('proses-testing-prediksi-cbrawit/', view_testing_prediksi_cbrawit.IndexView.as_view(), name='prediksi_cbrawit'),
    path('proses-testing-prediksi-cbrawit/<int:pk>/', view_testing_prediksi_cbrawit.DataDetailView.as_view(), name='detail_prediksi_cbrawit'),
    path('proses-testing-prediksi-cbrawit-create/', view_testing_prediksi_cbrawit.create, name='create_prediksi_cbrawit'),
    path('proses-testing-prediksi-cbrawit-edit/<int:pk>/', view_testing_prediksi_cbrawit.edit, name='edit_prediksi_cbrawit'),
    path('proses-testing-prediksi-cbrawit-delete/<int:pk>/', view_testing_prediksi_cbrawit.delete, name='delete_prediksi_cbrawit'),
    path('proses-testing-prediksi-cbmerah/', view_testing_prediksi_cbmerah.IndexView.as_view(), name='prediksi_cbmerah'),
    path('proses-testing-prediksi-cbmerah/<int:pk>/', view_testing_prediksi_cbmerah.DataDetailView.as_view(), name='detail_prediksi_cbmerah'),
    path('proses-testing-prediksi-cbmerah-create/', view_testing_prediksi_cbmerah.create, name='create_prediksi_cbmerah'),
    path('proses-testing-prediksi-cbmerah-edit/<int:pk>/', view_testing_prediksi_cbmerah.edit, name='edit_prediksi_cbmerah'),
    path('proses-testing-prediksi-cbmerah-delete/<int:pk>/', view_testing_prediksi_cbmerah.delete, name='delete_prediksi_cbmerah'),
]

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Data
from .forms import DataForm
from django.views.generic import ListView, DetailView


class IndexView(ListView):
    template_name = 'index.html'
    context_object_name = 'data_list'

    def get_queryset(self):
        return Data.objects.all()


class DataDetailView(DetailView):
    model = Data
    template_name = 'data-detail.html'


def create(request):
    if request.method == 'POST':
        form = DataForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home:home_view')
    form = DataForm()

    return render(request, 'create.html', {'form': form})


def edit(request, pk, template_name='edit.html'):
    data = get_object_or_404(Data, pk=pk)
    form = DataForm(request.POST or None, instance=data)
    if form.is_valid():
        form.save()
        return redirect('home:home_view')
    return render(request, template_name, {'form': form})


def delete(request, pk, template_name='confirm_delete.html'):
    contact = get_object_or_404(Data, pk=pk)
    if request.method == 'POST':
        contact.delete()
        return redirect('home:home_view')
    return render(request, template_name, {'object': contact})

home/views/normalisasi.py
from home.models import DataCbRawit, DataTestingCbRawit, DataTestingCbMerah
from home.models import DataCbMerah


def getnormalisasi_cbrawit():
    listdata = DataCbRawit.objects.all()
    listharga = DataCbRawit.objects.values_list('harga', flat=True)
    listproduksi = DataCbRawit.objects.values_list('produksi', flat=True)
    listketersediaan = DataCbRawit.objects.values_list('ketersediaan', flat=True)
    listpermintaan = DataCbRawit.objects.values_list('permintaan', flat=True)

    data_cbrawit = {
        'listdata': listdata,
        'listharga': listharga,
        'listproduksi': listproduksi,
        'listketersediaan': listketersediaan,
        'listpermintaan': listpermintaan
    }

    return getnormalisasi(data_cbrawit)


def getnormalisasi_cbmerah():
    listdata = DataCbMerah.objects.all()
    listharga = DataCbMerah.objects.values_list('harga', flat=True)
    listproduksi = DataCbMerah.objects.values_list('produksi', flat=True)
    listketersediaan = DataCbMerah.objects.values_list('ketersediaan', flat=True)
    listpermintaan = DataCbMerah.objects.values_list('permintaan', flat=True)

    data_cbmerah = {
        'listdata': listdata,
        'listharga': listharga,
        'listproduksi': listproduksi,
        'listketersediaan': listketersediaan,
        'listpermintaan': listpermintaan
    }

    return getnormalisasi(data_cbmerah)


def getnormalisasi_prediksi_cbrawit():
    listdata = DataTestingCbRawit.objects.all()
    listharga = DataTestingCbRawit.objects.values_list('harga', flat=True)
    listproduksi = DataTestingCbRawit.objects.values_list('produksi', flat=True)
    listketersediaan = DataTestingCbRawit.objects.values_list('ketersediaan', flat=True)
    listpermintaan = DataTestingCbRawit.objects.values_list('permintaan', flat=True)

    data_cbrawit = {
        'listdata': listdata,
        'listharga': listharga,
        'listproduksi': listproduksi,
        'listketersediaan': listketersediaan,
        'listpermintaan': listpermintaan
    }

    return getnormalisasi(data_cbrawit)


def getnormalisasi_prediksi_cbmerah():
    listdata = DataTestingCbMerah.objects.all()
    listharga = DataTestingCbMerah.objects.values_list('harga', flat=True)
    listproduksi = DataTestingCbMerah.objects.values_list('produksi', flat=True)
    listketersediaan = DataTestingCbMerah.objects.values_list('ketersediaan', flat=True)
    listpermintaan = DataTestingCbMerah.objects.values_list('permintaan', flat=True)

    data_cbmerah = {
        'listdata': listdata,
        'listharga': listharga,
        'listproduksi': listproduksi,
        'listketersediaan': listketersediaan,
        'listpermintaan': listpermintaan
    }

    return getnormalisasi(data_cbmerah)


def getnormalisasi(list_data):

    listdata = list_data['listdata']
    listharga = list_data['listharga']
    listproduksi = list_data['listproduksi']
    listketersediaan = list_data['listketersediaan']
    listpermintaan = list_data['listpermintaan']

    if len(listharga) > 0:
        minharga = min([int(i) for i in listharga])
        maxharga = max([int(i) for i in listharga])
    else:
        minharga = 0
        maxharga = 0

    if len(listproduksi) > 0:
        minproduksi = min([float(i) for i in listproduksi])
        maxproduksi = max([float(i) for i in listproduksi])
    else:
        minproduksi = 0
        maxproduksi = 0

    if len(listketersediaan) > 0:
        minketersediaan = min([float(i) for i in listketersediaan])
        maxketersediaan = max([float(i) for i in listketersediaan])
    else:
        minketersediaan = 0
        maxketersediaan = 0

    if len(listpermintaan) > 0:
        minpermintaan = min([float(i) for i in listpermintaan])
        maxpermintaan = max([float(i) for i in listpermintaan])
    else:
        minpermintaan = 0
        maxpermintaan = 0

    minvalue = {
        'type': 'Min',
        'harga': minharga,
        'produksi': minproduksi,
        'ketersediaan': minketersediaan,
        'permintaan': minpermintaan
    }

    maxvalue = {
        'type': 'Max',
        'harga': maxharga,
        'produksi': maxproduksi,
        'ketersediaan': maxketersediaan,
        'permintaan': maxpermintaan
    }

    newmin = 0.1
    newmax = 0.9

    n_data_all = []
    n_data = []
    n_harga = []
    n_produksi = []
    n_ketersediaan = []
    n_permintaan = []

    for x in listdata:
        data = {
            'no': x.no,
            'bulan': x.bulan,
            'tahun': x.tahun,
            'harga': x.harga,
            'produksi': x.produksi,
            'ketersediaan': x.ketersediaan,
            'permintaan': x.permintaan
        }
        n_data_all.append(data)

    for x in listdata:
        data = {
            'no': x.no,
            'bulan': x.bulan,
            'tahun': x.tahun,
            'harga': 0,
            'produksi': 0,
            'ketersediaan': 0,
            'permintaan': 0
        }
        n_data.append(data)

    for i, x in enumerate(listharga):
        minmax = maxvalue['harga'] - minvalue['harga']
        if minmax > 0:
            n = (((int(x) - minvalue['harga']) * (newmax - newmin)) / minmax) + newmin
            n_harga.append(n)
            n_data[i]['harga'] = float(n)

    for i, x in enumerate(listproduksi):
        minmax = maxvalue['produksi'] - minvalue['produksi']
        if minmax > 0:
            n = (((float(x) - minvalue['produksi']) * (newmax - newmin)) / minmax) + newmin
            n_produksi.append(n)
            n_data[i]['produksi'] = float(n)

    for i, x in enumerate(listketersediaan):
        minmax = maxvalue['ketersediaan'] - minvalue['ketersediaan']
        if minmax > 0:
            n = (((float(x) - minvalue['ketersediaan']) * (newmax - newmin)) / minmax) + newmin
            n_ketersediaan.append(n)
            n_data[i]['ketersediaan'] = float(n)

    for i, x in enumerate(listpermintaan):
        minmax = maxvalue['permintaan'] - minvalue['permintaan']
        if minmax > 0:
            n = (((float(x) - minvalue['permintaan']) * (newmax - newmin)) / minmax) + newmin
            n_permintaan.append(n)
            n_data[i]['permintaan'] = float(n)

    normalisasi = {
        'listdata': n_data_all,
        'min': minvalue,
        'max': maxvalue,
        'newmin': newmin,
        'newmax': newmax,
        'n_data': n_data
    }

    return normalisasi

home/views/view_cbmerah.py
from django.shortcuts import render, redirect, get_object_or_404
from home.models import cbMerah
from home.forms import cbMerahForm
from django.views.generic import ListView, DetailView


class IndexView(ListView):
    template_name = 'homedata_cbmerah.html'
    context_object_name = 'data_list'

    def get_queryset(self):
        return cbMerah.objects.all()


class DataView(ListView):
    template_name = 'home_cabaimerah.html'
    context_object_name = 'data_list'

    def get_queryset(self):
        return cbMerah.objects.all()


class DataDetailView(DetailView):
    model = cbMerah
    template_name = 'data-detailcbmerah.html'


def create(request):
    if request.method == 'POST':
        form = cbMerahForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home:homeview_cbmerah')
    form = cbMerahForm()

    return render(request, 'create_cbmerah.html', {'form': form})


def edit(request, pk, template_name='edit_cbmerah.html'):
    data = get_object_or_404(cbMerah, pk=pk)
    form = cbMerahForm(request.POST or None, instance=data)
    if form.is_valid():
        form.save()
        return redirect('home:homeview_cbmerah')
    return render(request, template_name, {'form': form})


def delete(request, pk, template_name='confirm_deletecbmerah.html'):
    contact = get_object_or_404(cbMerah, pk=pk)
    if request.method == 'POST':
        contact.delete()
        return redirect('home:homeview_cbmerah')
    return render(request, template_name, {'object': contact})

home/views/view_chart_cbmerah.py
from django.views.generic import ListView

from home.models import DataMseCbMerah


class IndexView(ListView):
    template_name = 'proses_mse_cbmerah.html'
    context_object_name = 'data'

    def get_queryset(self):

        data_mse = 0
        db = DataMseCbMerah.objects.all()

        if len(db) > 0:
            data_mse = db[0].mse

        context = {
            'data_mse': data_mse
        }

        return context

home/views/view_chart_cbrawit.py
from django.http import JsonResponse
from django.views.generic import ListView

from home.models import DataDenormalisasiCbRawit


class IndexView(ListView):
    model = DataDenormalisasiCbRawit
    template_name = 'proses_chart_cbrawit.html'


def get_chart(request):

    db = DataDenormalisasiCbRawit.objects.all()

    labels = []
    data1 = []
    data2 = []

    for x in db:
        labels.append(x.bulan)
        data1.append(x.denormalisasi)
        data2.append(x.hasil)

    return JsonResponse(data={
        'labels': labels,
        'data1': data1,
        'data2': data2
    })

home/views/view_data.py
from django.shortcuts import render, redirect, get_object_or_404
from home.models import Data
from home.forms import DataForm
from django.views.generic import ListView, DetailView


class IndexView(ListView):
    template_name = 'home_data.html'
    context_object_name = 'data_list'

    def get_queryset(self):
        return Data.objects.all()


class DataView(ListView):
    template_name = 'home_cabairawit.html'
    context_object_name = 'data_list'

    def get_queryset(self):
        return Data.objects.all()


class DataDetailView(DetailView):
    model = Data
    template_name = 'data-detail.html'


def create(request):
    if request.method == 'POST':
        form = DataForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home:home_view')
    form = DataForm()

    return render(request, 'create.html', {'form': form})


def edit(request, pk, template_name='edit.html'):
    data = get_object_or_404(Data, pk=pk)
    form = DataForm(request.POST or None, instance=data)
    if form.is_valid():
        form.save()
        return redirect('home:home_view')
    return render(request, template_name, {'form': form})


def delete(request, pk, template_name='confirm_delete.html'):
    contact = get_object_or_404(Data, pk=pk)
    if request.method == 'POST':
        contact.delete()
        return redirect('home:home_view')
    return render(request, template_name, {'object': contact})

home/views/view_denormalisasi_cbmerah.py
from django.views.generic import ListView

from home.models import DataDenormalisasiCbMerah


class IndexView(ListView):
    template_name = 'proses_denormalisasi_cbmerah.html'
    context_object_name = 'data'

    def get_queryset(self):

        data_denormalisasi = []
        db = DataDenormalisasiCbMerah.objects.all()

        for i, x in enumerate(db):
            d = {
                'no': x.no,
                'denormalisasi': x.denormalisasi,
                'hasil': x.hasil
            }
            data_denormalisasi.append(d)

        context = {
            'data_denormalisasi': data_denormalisasi
        }

        return context

home/templates/confirm_delete_cbmerah.html
{% extends 'base.html' %}
{% block content %}

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_content">

            </div>
        </div>
    </div>

    <div class="right_col">
        <div class="container">
            <br/><br/><br/>

            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="alert alert-warning">
                        <center>Are you sure you want to delete?</center>
                    </div>
                </div>
                <center>
                    <button type="submit" class="btn btn-danger">delete</button>
                </center>
            </form>
        </div>
    </div>

{% endblock %}

home/templates/proses_mse_cbrawit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}

<!-- page content -->
<div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="row">

        <div class="x_content"></div>
            <div class="" role="tabpanel" data-example-id="togglable-tabs">
                <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                    <li role="presentation" class="active"><a href="{% url 'home:data_cbrawit' %}" id="home-tab" role="tab" aria-expanded="true">Data</a>
                    </li>
                    {% if request.session.status == '1' %}
                    <li role="presentation" class=""><a href="{% url 'home:normalisasi_cbrawit' %}" role="tab" id="profile-tab" aria-expanded="false">Normalisasi</a>
                    </li>
                    <li role="presentation" class=""><a href="{% url 'home:training_cbrawit' %}" role="tab" id="profile-tab2" aria-expanded="false">Proses Training</a>
                    </li>
                    <li role="presentation" class=""><a href="{% url 'home:testing_cbrawit' %}" role="tab" id="profile-tab2" aria-expanded="false">Proses Testing</a>
                    </li>
                    <li role="presentation" class=""><a href="{% url 'home:mse_cbrawit' %}" role="tab" id="profile-tab2" aria-expanded="false">Nilai MSE</a>
                    </li>
                    <li role="presentation" class=""><a href="{% url 'home:denormalisasi_cbrawit' %}" role="tab" id="profile-tab2" aria-expanded="false">Denormalisasi</a>
                    </li>
                    {% endif %}
                    <li role="presentation" class=""><a href="{% url 'home:prediksi_cbrawit' %}" role="tab" id="profile-tab2" aria-expanded="false">Hasil Prediksi</a>
                    </li>
                    <li role="presentation" class=""><a href="{% url 'home:chart_cbrawit' %}" role="tab" id="profile-tab2" aria-expanded="false">Grafik</a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h3><b>Mean Square Error (MSE)</b></h3>
                    <div class="clearfix"></div>
                </div>

                <h4><b>{{ data.data_mse }}</b></h4>
            </div>
        </div>

    </div>
</div>
<!-- /page content -->
{% endblock %}

home/templates/proses_testing_prediksi_cbmerah.html
{% extends 'base.html' %}
{% block content %}
<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">

            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="x_content"></div>
            <div class="" role="tabpanel" data-example-id="togglable-tabs">
                <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                    <li role="presentation" class="active"><a href="{% url 'home:data_cbmerah' %}" id="home-tab" role="tab" aria-expanded="true">Data</a>
                    </li>
                    {% if request.session.status == '1' %}
                    <li role="presentation" class=""><a href="{% url 'home:normalisasi_cbmerah' %}" role="tab" id="profile-tab" aria-expanded="false">Normalisasi</a>
                    </li>
                    <li role="presentation" class=""><a href="{% url 'home:training_cbmerah' %}" role="tab" id="profile-tab2" aria-expanded="false">Proses Training</a>
                    </li>
                    <li role="presentation" class=""><a href="{% url 'home:testing_cbmerah' %}" id="profile-tab2" aria-expanded="false">Proses Testing</a>
                    </li>
                    <li role="presentation" class=""><a href="{% url 'home:mse_cbmerah' %}" role="tab" id="profile-tab2" aria-expanded="false">Nilai MSE</a>
                    </li>
                    <li role="presentation" class=""><a href="{% url 'home:denormalisasi_cbmerah' %}" role="tab" id="profile-tab2" aria-expanded="false">Denormalisasi</a>
                    </li>
                    {% endif %}
                    <li role="presentation" class=""><a href="{% url 'home:prediksi_cbmerah' %}" role="tab" id="profile-tab2" aria-expanded="false">Hasil Prediksi</a>
                    </li>
                    <li role="presentation" class=""><a href="{% url 'home:chart_cbmerah' %}" role="tab" id="profile-tab2" aria-expanded="false">Grafik</a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Data Prediksi Cabai Merah Besar</h2>
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">
                    <table id="datatable-buttons" class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th width="5%"><center>No</center></th>
                            <th width="20%">Harga</th>
                            <th width="20%">Produksi (KW)</th>
                            <th width="20%">Ketersediaan (TON)</th>
                            <th width="20%">Prediksi</th>
                            <th width="20%"><a class="btn btn-primary" href="{% url 'home:create_prediksi_cbmerah' %}">Tambah</a></th>
                        </tr>
                        </thead>

                        <tbody>
                        {% for data in data_list %}
                        <tr>
                            <td><a href="{% url 'home:detail_prediksi_cbmerah' data.pk %}"><center>{{ data.no }}</center></a></td>
                            <td>{{ data.harga }}</td>
                            <td>{{ data.produksi }}</td>
                            <td>{{ data.ketersediaan }}</td>
                            <td>{{ data.permintaan }}</td>
                            <td>
                                <a href="{% url 'home:edit_prediksi_cbmerah' data.pk %}">
                                    <button type="button" class="btn btn-success">Edit</button>
                                </a>
                                <a href="{% url 'home:delete_prediksi_cbmerah' data.pk %}">
                                    <button type="button" class="btn btn-danger">Hapus</button>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->

{% endblock %}

home/templates/proses_testing_prediksi_cbrawit.html
{% extends 'base.html' %}
{% block content %}
<!-- page content -->
<div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
        </div>
      </div>

      <div class="clearfix"></div>

        <div class="row">
            <div class="x_content"></div>
            <div class="" role="tabpanel" data-example-id="togglable-tabs">
                <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                    <li role="presentation" class="active"><a href="{% url 'home:data_cbrawit' %}" id="home-tab" role="tab" aria-expanded="true">Data</a>
                    </li>
                    {% if request.session.status == '1' %}
                    <li role="presentation" class=""><a href="{% url 'home:normalisasi_cbrawit' %}" role="tab" id="profile-tab" aria-expanded="false">Normalisasi</a>
                    </li>
                    <li role="presentation" class=""><a href="{% url 'home:training_cbrawit' %}" role="tab" id="profile-tab2" aria-expanded="false">Proses Training</a>
                    </li>
                    <li role="presentation" class=""><a href="{% url 'home:testing_cbrawit' %}" role="tab" id="profile-tab2" aria-expanded="false">Proses Testing</a>
                    </li>
                    <li role="presentation" class=""><a href="{% url 'home:mse_cbrawit' %}" role="tab" id="profile-tab2" aria-expanded="false">Nilai MSE</a>
                    </li>
                    <li role="presentation" class=""><a href="{% url 'home:denormalisasi_cbrawit' %}" role="tab" id="profile-tab2" aria-expanded="false">Denormalisasi</a>
                    </li>
                    {% endif %}
                    <li role="presentation" class=""><a href="{% url 'home:prediksi_cbrawit' %}" role="tab" id="profile-tab2" aria-expanded="false">Hasil Prediksi</a>
                    </li>
                    <li role="presentation" class=""><a href="{% url 'home:chart_cbrawit' %}" role="tab" id="profile-tab2" aria-expanded="false">Grafik</a>
                    </li>
                </ul>
            </div>
        </div>
        
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>Data Prediksi Cabai Rawit</h2>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <table id="datatable-buttons" class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th width="5%"><center>No</center></th>
                    <th width="20%">Harga</th>
                    <th width="20%">Produksi (KW)</th>
                    <th width="20%">Ketersediaan (TON)</th>
                    <th width="20%">Prediksi</th>
                    <th width="20%">
                        <a class="btn btn-primary" href="{% url 'home:create_prediksi_cbrawit' %}">Tambah</a>
                    </th>
                   
                  </tr>
                </thead>

                <tbody>
                    {% for data in data_list %}
                      <tr>
                          <td><a href="{% url 'home:detail_prediksi_cbrawit' data.pk %}"><center>{{ data.no }}</center></a></td>
                          <td>{{ data.harga }}</td>
                          <td>{{ data.produksi }}</td>
                          <td>{{ data.ketersediaan }}</td>
                          <td>{{ data.permintaan }}</td>
                          <td>
                              <a href="{% url 'home:edit_prediksi_cbrawit' data.pk %}">
                                  <button type="button" class="btn btn-success">Edit</button>
                              </a>
                              <a href="{% url 'home:delete_prediksi_cbrawit' data.pk %}">
                                  <button type="button" class="btn btn-danger">Hapus</button>
                              </a>
                          </td>
                      </tr>
                    {% endfor %}
                </tbody>

              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /page content -->

  {% endblock %}